/** Browse facets for the full iptv-org index (Search filters). */

export const CATALOG_CATEGORIES = [
  "Sports",
  "News",
  "Entertainment",
  "Movies",
  "Series",
  "Kids",
  "Music",
  "Religious",
  "Documentary",
  "Cooking",
  "Culture",
  "General",
  "Comedy",
  "Animation",
  "Education",
  "Lifestyle",
  "Outdoor",
  "Business",
  "Shop",
  "Legislative",
  "Weather",
  "Uncategorized",
] as const;

export const CATALOG_COUNTRIES: { code: string; label: string }[] = [
  { code: "us", label: "United States" },
  { code: "ca", label: "Canada" },
  { code: "uk", label: "United Kingdom" },
  { code: "za", label: "South Africa" },
  { code: "in", label: "India" },
  { code: "de", label: "Germany" },
  { code: "fr", label: "France" },
  { code: "br", label: "Brazil" },
  { code: "mx", label: "Mexico" },
  { code: "es", label: "Spain" },
  { code: "it", label: "Italy" },
  { code: "au", label: "Australia" },
  { code: "nl", label: "Netherlands" },
  { code: "tr", label: "Turkey" },
  { code: "ar", label: "Argentina" },
  { code: "cl", label: "Chile" },
  { code: "pl", label: "Poland" },
  { code: "ru", label: "Russia" },
  { code: "se", label: "Sweden" },
  { code: "cn", label: "China" },
  { code: "jp", label: "Japan" },
  { code: "kr", label: "Korea" },
  { code: "id", label: "Indonesia" },
  { code: "pk", label: "Pakistan" },
  { code: "ng", label: "Nigeria" },
  { code: "ke", label: "Kenya" },
  { code: "eg", label: "Egypt" },
  { code: "world", label: "World / Other" },
];
